from setuptools import setup
setup(name="OldMan",
      author="Benjamin Cogrel",
      author_email="benjamin.cogrel@bcgl.fr",
      url="https://github.com/oldm/oldman",
      version="0.2",
      description="Object Linked Data Mapper",
      long_description=open('README.rst').read(),
      packages=['oldman',
                'oldman.mediation',
                'oldman.model',
                'oldman.resource',
                'oldman.parsing',
                'oldman.parsing.schema',
                'oldman.rest',
                'oldman.store',
                'oldman.schema',
                'oldman.utils',
                'oldman.validation'
      ],
      include_package_data=True,
      #zip_safe = False,
      install_requires=['rdflib',
                        'rdflib-jsonld',
                        'SPARQLWrapper',
                        'validate_email',
                        'dogpile.cache',
                        'requests',
                        'negotiator'
      ],
      license="BSD",
      classifiers=[
          'Development Status :: 3 - Alpha',
          'Intended Audience :: Developers',
          'License :: OSI Approved :: BSD License',
          'Programming Language :: Python',
          'Programming Language :: Python :: 2',
          'Programming Language :: Python :: 2.7',
          'Topic :: Software Development :: Libraries',
      ]
      )
