from setuptools import setup
setup(name="OldMan",
      author="Benjamin Cogrel",
      author_email="benjamin.cogrel@bcgl.fr",
      url="https://github.com/oldm/oldman",
      version="0.2",
      description="Object Linked Data Mapper",
      long_description=open('README.rst').read(),
      packages=['oldman',
                'oldman.client',
                'oldman.client.hydra',
                'oldman.client.mediation',
                'oldman.client.model',
                'oldman.client.parsing',
                'oldman.client.rest',
                'oldman.core.model',
                'oldman.core.parsing',
                'oldman.core.parsing.schema',
                'oldman.core.resource',
                'oldman.core.session',
                'oldman.core.utils',
                'oldman.core.validation',
                'oldman.storage',
                'oldman.storage.hydra',
                'oldman.storage.model',
                'oldman.storage.model.conversion',
                'oldman.storage.store'
      ],
      include_package_data=True,
      #zip_safe = False,
      install_requires=['rdflib',
                        'rdflib-jsonld',
                        'SPARQLWrapper',
                        'validate_email',
                        'dogpile.cache',
                        'requests',
                        'negotiator',
                        'networkx',
                        'rfc3987'
      ],
      license="BSD",
      classifiers=[
          'Development Status :: 3 - Alpha',
          'Intended Audience :: Developers',
          'License :: OSI Approved :: BSD License',
          'Programming Language :: Python',
          'Programming Language :: Python :: 2',
          'Programming Language :: Python :: 2.7',
          'Topic :: Software Development :: Libraries',
      ]
      )
